version: "3.9"
services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "hezzl"
      PGPORT: 5436
    expose:
      - 5436
    ports:
      - 5436:5436

  clickhouse:
    image: "clickhouse/clickhouse-server"
    ports:
      - 8123:8123

  redis:
    image: "redis"
    ports:
      - 6379:6379

  nats:
    image: "nats"
    networks:
      nats:
    ports:
      - 4222:4222

  app:
    build: .
    container_name: "app"
    ports:
      - 8090:8090

networks:
  nats:
